AllCops:
  DisabledByDefault: true
  NewCops: enable

Lint:                             { Enabled: true  }

Layout:                           { Enabled: true  }

Layout/LineLength:                { Enabled: false }

Style/AndOr:                      { Enabled: true  }
Style/DefWithParentheses:         { Enabled: true  }
Style/EmptyLiteral:               { Enabled: true  }
Style/For:                        { Enabled: true  }
Style/HashSyntax:                 { Enabled: true  }
Style/MethodDefParentheses:       { Enabled: true  }
Style/MultilineIfThen:            { Enabled: true  }
Style/Not:                        { Enabled: true  }
Style/ParenthesesAroundCondition: { Enabled: true  }

Naming/MethodParameterName:       { Enabled: true  }
Naming/VariableName:              { Enabled: true  }

